# Generated by Django 5.0.3 on 2025-06-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allblog', '0002_blogs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='Titleblog',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='blogs',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogs',
            name='content',
            field=models.CharField(default='', max_length=320),
        ),
        migrations.AddField(
            model_name='blogs',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='content',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(default='', upload_to='allblog/images'),
        ),
    ]
