# Generated by Django 5.0.3 on 2025-06-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allblog', '0003_blogs_titleblog_blogs_comments_blogs_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Titleblog',
            field=models.CharField(default='', max_length=220),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=models.CharField(default='', max_length=720),
        ),
    ]
