# Generated by Django 5.0.3 on 2025-06-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allblog', '0004_alter_blogs_titleblog_alter_blogs_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
