# Generated by Django 5.0.3 on 2025-06-21 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allblog', '0009_remove_blogs_username_blogs_user_alter_blogs_blog_id'),
        ('signup', '0002_alter_signup_password_alter_signup_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.signup'),
        ),
    ]
