# Generated by Django 5.0.3 on 2025-06-21 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allblog', '0010_alter_blogs_user'),
        ('signup', '0002_alter_signup_password_alter_signup_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.signup'),
        ),
    ]
