# Generated by Django 5.0.3 on 2025-06-21 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allblog', '0012_rename_comments_blogs_comment_comments_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
